#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

leftwm command "UnloadTheme"

pkill sxhkd
pkill pmenu
pkill picom 
eww kill
pkill trayer
