#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot compton or picom if it exists
picom --experimental-backends &> /dev/null & 

#set the theme.toml config
leftwm command "LoadTheme  $SCRIPTPATH/theme.toml"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

sxhkd &

sh ~/.local/bin/pmenu.sh

eww daemon
eww open bar_0
eww open bar_1
eww open bar_2

trayer --edge top --width 10 --height 25 --align right --monitor 0 & disown
