modkey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "", "", "", "r", "t", "y", "", "", "", "ﭮ"]

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "c"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Alt"]
key = "r"

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Alt"]
key = "q"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "GotoTag"
value = "10"
modifier = ["modkey"]
key = "0"

[[keybind]]
command = "GotoTag"
value = "11"
modifier = ["modkey", "Control"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "12"
modifier = ["modkey", "Control"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "13"
modifier = ["modkey", "Control"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "14"
modifier = ["modkey", "Control"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "15"
modifier = ["modkey", "Control"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "16"
modifier = ["modkey", "Control"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "17"
modifier = ["modkey", "Control"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "18"
modifier = ["modkey", "Control"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "19"
modifier = ["modkey", "Control"]
key = "9"

[[keybind]]
command = "GotoTag"
value = "20"
modifier = ["modkey", "Control"]
key = "0"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "10"
modifier = ["modkey", "Shift"]
key = "0"

[[keybind]]
command = "MoveToTag"
value = "11"
modifier = ["modkey", "Shift", "Control"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "12"
modifier = ["modkey", "Shift", "Control"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "13"
modifier = ["modkey", "Shift", "Control"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "14"
modifier = ["modkey", "Shift", "Control"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "15"
modifier = ["modkey", "Shift", "Control"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "16"
modifier = ["modkey", "Shift", "Control"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "17"
modifier = ["modkey", "Shift", "Control"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "18"
modifier = ["modkey", "Shift", "Control"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "19"
modifier = ["modkey", "Shift", "Control"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "20"
modifier = ["modkey", "Shift", "Control"]
key = "0"

